version: "3.1"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./wordpress:/var/www/html/
        links:
            - "db:database"
    db:
        image: mariadb:10.2
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_USER: admin 
            MYSQL_PASSWORD: devpass
            MYSQL_ROOT_PASSWORD: devpass 
        volumes:
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: devpass
            MYSQL_ROOT_PASSWORD: devpass 
volumes:
    persistent:
